/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsyncRouterView: typeof import('./src/components/AsyncRouterView.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    LoadingAnimation: typeof import('./src/components/LoadingAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
