version: "3"
services:
  vue3-app:
    container_name: vue3-app
    build: .
    image: vue
    ports:
      - 80:80
  nginx:
    container_name: nginx-app
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - vue3-app
