/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsyncRouterView: typeof import('./components/AsyncRouterView.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    HighlightSearchText: typeof import('./components/HighlightSearchText.vue')['default']
    InputCheckbox: typeof import('./components/input/checkbox/index.vue')['default']
    InputCheckboxGroup: typeof import('./components/input/checkbox/group.vue')['default']
    InputRadio: typeof import('./components/input/radio/index.vue')['default']
    InputRadioGroup: typeof import('./components/input/radio/group.vue')['default']
    InputTextField: typeof import('./components/input/TextField.vue')['default']
    Modal: typeof import('./components/modal/index.vue')['default']
    ModalConfirm: typeof import('./components/modal/Confirm.vue')['default']
    Overlay: typeof import('./components/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableContainer: typeof import('./components/TableContainer/index.vue')['default']
  }
}
